import Foundation

/// The fixed phrases with bundled StepSafe-voice clips (Phrases/phrases.json, generated by
/// scripts/gen-phrases.ts). Pure, so the mapping is unit-tested.
struct PhraseBook {
    struct Entry: Codable, Equatable { var id: String; var en: String; var es: String }
    private struct File: Codable { var phrases: [Entry] }

    let entries: [Entry]
    private let byText: [String: String]

    init(json: Data) throws {
        entries = try JSONDecoder().decode(File.self, from: json).phrases
        var map: [String: String] = [:]
        for e in entries { map[e.en] = e.id; map[e.es] = e.id }
        byText = map
    }

    /// Phrase ids covering `text` in order: the longest fixed phrase at each position, then ". " (what's-ahead
    /// joins phrases that way; phrases may contain periods themselves). nil if any part is not a fixed phrase
    /// (then the caller speaks the text instead).
    func ids(for text: String) -> [String]? {
        var rest = Substring(text), ids: [String] = []
        while !rest.isEmpty {
            guard let match = byText.keys.filter({ rest.hasPrefix($0) }).max(by: { $0.count < $1.count }),
                  let id = byText[match] else { return nil }
            ids.append(id)
            rest = rest.dropFirst(match.count)
            if rest.hasPrefix(". ") { rest = rest.dropFirst(2) } else if !rest.isEmpty { return nil }
        }
        return ids.isEmpty ? nil : ids
    }

    /// Clip names "<id>.<lang>" for `text`, or nil (speech fallback) when the text is not fixed or any clip
    /// is missing for that language.
    func clipNames(for text: String, lang: String, exists: (String) -> Bool) -> [String]? {
        guard let names = ids(for: text)?.map({ "\($0).\(lang)" }), names.allSatisfy(exists) else { return nil }
        return names
    }
}
