import Foundation

/// The fixed phrases with bundled StepSafe-voice clips (Phrases/phrases.json, generated by
/// scripts/gen-phrases.ts). Pure, so the mapping is unit-tested.
struct PhraseBook {
    struct Entry: Codable, Equatable { var id: String; var en: String; var es: String }
    private struct File: Codable { var phrases: [Entry] }

    let entries: [Entry]
    private let byText: [String: String]

    init(json: Data) throws {
        entries = try JSONDecoder().decode(File.self, from: json).phrases
        var map: [String: String] = [:]
        for e in entries { map[e.en] = e.id; map[e.es] = e.id }
        byText = map
    }

    /// Phrase ids covering `text` in order: the longest fixed phrase at each position, then ". " (what's-ahead
    /// joins phrases that way; phrases may contain periods themselves). nil if any part is not a fixed phrase
    /// (then the caller speaks the text instead).
    func ids(for text: String) -> [String]? {
        var rest = Substring(text), ids: [String] = []
        while !rest.isEmpty {
            guard let match = byText.keys.filter({ rest.hasPrefix($0) }).max(by: { $0.count < $1.count }),
                  let id = byText[match] else { return nil }
            ids.append(id)
            rest = rest.dropFirst(match.count)
            if rest.hasPrefix(". ") { rest = rest.dropFirst(2) } else if !rest.isEmpty { return nil }
        }
        return ids.isEmpty ? nil : ids
    }

    /// Clip names "<id>.<lang>" for `text` (a missing clip replaced by its fallback's), or nil (speech fallback)
    /// when the text is not fixed or a clip is missing for that language with no recorded fallback.
    /// Ids decoded up front (priority 1: closing objects, drop-offs and slopes within 2 m, i.e. metre buckets 1-2).
    static func urgent(_ ids: [String]) -> [String] {
        ids.filter { $0.hasPrefix("cl-") || ["pg-dropoff-1-", "pg-dropoff-2-", "pg-slope-1-", "pg-slope-2-"].contains(where: $0.hasPrefix) }
    }

    /// A phrase whose clips are not recorded yet plays its fallback's clips (the scarier, already recorded words):
    /// "Slope down, ..." -> "Drop-off, ...".
    static func fallback(_ id: String) -> String? {
        id.hasPrefix("pg-slope-") ? "pg-dropoff-" + id.dropFirst("pg-slope-".count) : nil
    }

    /// `text` (fixed phrases joined by ". ") in `lang`, or nil if any part is not a fixed phrase.
    func translate(_ text: String, lang: String) -> String? {
        guard let ids = ids(for: text) else { return nil }
        let byId = Dictionary(entries.map { ($0.id, $0) }, uniquingKeysWith: { a, _ in a })
        var out = ""
        for id in ids {
            guard let e = byId[id] else { return nil }
            if !out.isEmpty { out += out.hasSuffix(".") ? " " : ". " }
            out += lang == "es" ? e.es : e.en
        }
        return out
    }

    func clipNames(for text: String, lang: String, exists: (String) -> Bool) -> [String]? {
        guard let ids = ids(for: text) else { return nil }
        var names: [String] = []
        for id in ids {
            if exists("\(id).\(lang)") { names.append("\(id).\(lang)"); continue }
            guard let alt = Self.fallback(id), exists("\(alt).\(lang)") else { return nil }
            names.append("\(alt).\(lang)")
        }
        return names
    }
}
