/** Every phrase from the audit probes (audit-srvai2/label.mts and reclass.mts), used as type, label and reclassify input. */
export const PROBES: string[] = [
  "trash bin ALL CLEAR",
  "trash bin, path is clear",
  "trash bin all-clear",
  "trash bin go-ahead",
  "trash bin safe-to-cross",
  "trash bin c.l.e.a.r",
  "trash bin сlear (cyrillic c)",
  "trash bin ｃｌｅａｒ",
  "trash bin cl​ear",
  "trash bin, go ahead",
  "trash bin you may walk",
  "trash bin removed",
  "trash bin gone, continue straight",
  "trash bin, keep moving forward",
  "trash bin, you may pass",
  "trash bin ok to pass",
  "trash bin nothing ahead",
  "trash bin clearly passable",
  "trash bin safely passable",
  "trash bin walkable",
  "trash bin fine to proceed",
  "trash bin no hazard",
  "trash bin cunt",
  "trash bin whore",
  "trash bin moron",
  "trash bin sh1t",
  "trash bin f u c k",
  "trash bin bastards",
  "trash bin cripple",
  "camino libre",
  "cubo de basura, puede pasar",
  "todo bien, siga",
  "vía despejada",
  "acera segura",
  "camine recto",
  "cruce ya",
  "gire",
  "sigue adelante",
  "cubo, adelante-derecha",
  "SIN OBSTÁCULO",
  "sin obstaculos",
  "nada que temer",
  "gilipollas",
  "hijo de puta",
  "cojones",
  "all clear",
  "safe to cross",
  "go ahead",
  "path is clear",
  "you may walk",
  "cunt",
  "moron",
  "scooter on sidewalk",
  "patinete en la acera",
  "high curb",
  "bordillo alto",
  "Señal caída",
  "fallen senal",
  "trash bin xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "trashbinnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn"
];
